; ================================================================
;  ESTACION — estación base (WiFi + Firebase + LoRa)
;  Heltec WiFi LoRa 32 V3 (ESP32-S3 + SX1262)
; ================================================================

[env:heltec_wifi_lora_32_V3]
platform  = espressif32
board     = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed    = 921600

; Versiones fijadas a propósito — no actualizar sin probar
lib_deps =
  jgromes/RadioLib @ ^6.4.0
  mobizt/Firebase ESP32 Client @ ^4.4.14
  bblanchon/ArduinoJson @ ^6.21.0

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -I../shared

build_src_filter =
  +<*>
  +<../../shared/>
